(()=>{
'use strict';
const S=()=>window.SomtodayPlusStorage?.get();
let lastCustomTitle=null;
let clockTimer=null;
const FONT_MAP={system:'Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',inter:'Inter,system-ui,sans-serif',roboto:'Roboto,Arial,sans-serif',poppins:'Poppins,Inter,sans-serif',serif:'Georgia,"Times New Roman",serif',mono:'ui-monospace,SFMono-Regular,Consolas,monospace'};
function setClass(name,on){document.documentElement.classList.toggle(name,!!on)}
function allClasses(s){
  const map={
    'stp-privacy':s.privacyMode,'stp-privacy-hover':s.privacyHoverReveal,'stp-focus':s.focusMode,'stp-selectable':s.selectableText,'stp-hide-scrollbar':s.hideScrollbar,
    'stp-sticky-topbar':s.stickyTopbar,'stp-dim-weekends':s.dimWeekends||s.weekendFade,'stp-schedule-accent':s.scheduleAccent,'stp-schedule-compact':s.scheduleCompact,
    'stp-current-lesson':s.currentLessonHighlight,'stp-hide-unread':s.hideUnreadBadge,'stp-hide-profile':s.hideProfilePicture,'stp-hide-side-labels':s.hideSideLabels,
    'stp-sidebar-compact':s.sidebarCompact,'stp-page-transitions':s.pageTransitions,'stp-button-animations':s.buttonAnimations,'stp-homework-highlight':s.homeworkHighlight,
    'stp-exam-highlight':s.examHighlight,'stp-grade-coloring':s.gradeColoring,'stp-grade-reveal':s.gradeReveal,'stp-dyslexia':s.dyslexiaFriendly,
    'stp-large-targets':s.largerClickTargets,'stp-underline-links':s.underlineLinks,'stp-blur-panels':s.blurBackgroundPanels,'stp-monochrome':s.monochromeMode,
    'stp-dev-outline':s.devOutline
  };
  Object.entries(map).forEach(([c,v])=>setClass(c,v));
}
function clearFeatureClasses(){[...document.documentElement.classList].filter(c=>c.startsWith('stp-')&&!['stp-rounded','stp-animations','stp-compact','stp-gradient','stp-disabled'].includes(c)).forEach(c=>document.documentElement.classList.remove(c))}
function applyTitle(s){if(s.customTitleEnabled&&s.customTitle?.trim()){if(lastCustomTitle===null)lastCustomTitle=document.title;document.title=s.customTitle.trim()}else if(lastCustomTitle!==null){document.title=lastCustomTitle;lastCustomTitle=null}}
function applyDensity(s){const r=document.documentElement;r.style.setProperty('--stp-font-scale',String(s.fontScale||1));r.style.setProperty('--stp-card-gap',`${s.cardGap??12}px`);r.style.setProperty('--stp-font-family',FONT_MAP[s.fontFamily]||FONT_MAP.system);r.dataset.stpMenuDensity=s.menuDensity||'normal'}
function applyCustomCss(s){let style=document.getElementById('stp-custom-css');if(!s.customCssEnabled||!s.customCss?.trim()){style?.remove();return}if(!style){style=document.createElement('style');style.id='stp-custom-css';document.head.appendChild(style)}style.textContent=s.customCss}
function applyAlias(s){document.querySelectorAll('[data-stp-original-name]').forEach(el=>{if(!s.aliasEnabled){el.textContent=el.dataset.stpOriginalName;delete el.dataset.stpOriginalName}});if(!s.aliasEnabled||!s.displayAlias?.trim())return;const selectors=['sl-account-modal-header .naam','.gebruiker-naam','[class*=gebruikersnaam]','[class*=user-name]'];for(const sel of selectors)document.querySelectorAll(sel).forEach(el=>{if(!el.dataset.stpOriginalName)el.dataset.stpOriginalName=el.textContent;el.textContent=s.displayAlias.trim()})}
function weekNumber(d=new Date()){const date=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));date.setUTCDate(date.getUTCDate()+4-(date.getUTCDay()||7));const yearStart=new Date(Date.UTC(date.getUTCFullYear(),0,1));return Math.ceil((((date-yearStart)/86400000)+1)/7)}
function updateClock(s){let el=document.getElementById('stp-clock-chip');if(!s.showClock&&!s.showWeekNumber){el?.remove();clearInterval(clockTimer);clockTimer=null;return}if(!el){el=document.createElement('div');el.id='stp-clock-chip';document.body.appendChild(el)}const now=new Date(),parts=[];if(s.showClock)parts.push(now.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}));if(s.showWeekNumber)parts.push(`week ${weekNumber(now)}`);el.textContent=parts.join(' · ');if(!clockTimer)clockTimer=setInterval(()=>S().then(updateClock),30000)}
function decorate(){
  document.querySelectorAll('sl-rooster-item,[class*=rooster-item],[class*=afspraak]').forEach(el=>el.classList.add('stp-enhanced-schedule-item'));
  document.querySelectorAll('.cijfer,[class*=cijfer]').forEach(el=>el.classList.add('stp-grade-target'));
  document.querySelectorAll('[class*=huiswerk],[class*=homework]').forEach(el=>el.classList.add('stp-homework-target'));
  document.querySelectorAll('[class*=toets],[class*=exam],[class*=proefwerk]').forEach(el=>el.classList.add('stp-exam-target'));
}
async function apply(){const s=await S();if(!s)return;if(!s.enabled){clearFeatureClasses();applyTitle({...s,customTitleEnabled:false});applyCustomCss({...s,customCssEnabled:false});updateClock({...s,showClock:false,showWeekNumber:false});return}allClasses(s);applyDensity(s);applyTitle(s);applyCustomCss(s);applyAlias(s);updateClock(s);decorate()}
function toast(text){let t=document.querySelector('.stp-toast');if(!t){t=document.createElement('div');t.className='stp-toast';document.body.appendChild(t)}t.textContent=text;t.classList.remove('show');requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2200)}
function toggleQuick(key,label){S().then(async s=>{if(!s.enabled)return toast('Somtoday PLUS+ staat uit');const next=!s[key];await SomtodayPlusStorage.set({[key]:next});toast(`${label}: ${next?'aan':'uit'}`)})}
function gradeCalculator(){if(document.getElementById('stp-grade-calc'))return;const root=document.createElement('div');root.id='stp-grade-calc';root.innerHTML=`<div><button class="stp-mini-close">×</button><h3>Cijferdoel berekenen</h3><p>Vul je huidige gemiddelde, huidige totale weging en de weging van je volgende toets in.</p><label>Huidig gemiddelde<input data-c="avg" type="number" min="1" max="10" step="0.01" value="6.5"></label><label>Huidige totale weging<input data-c="weight" type="number" min="0" step="0.1" value="10"></label><label>Nieuwe toets weging<input data-c="newWeight" type="number" min="0.1" step="0.1" value="1"></label><label>Gewenst gemiddelde<input data-c="target" type="number" min="1" max="10" step="0.01" value="7"></label><output></output></div>`;document.body.appendChild(root);const calc=()=>{const g=k=>Number(root.querySelector(`[data-c="${k}"]`).value),a=g('avg'),w=g('weight'),nw=g('newWeight'),t=g('target'),needed=((t*(w+nw))-(a*w))/nw,out=root.querySelector('output');out.textContent=Number.isFinite(needed)?(needed>10?`Je zou ongeveer ${needed.toFixed(2)} moeten halen; dat ligt boven 10.`:needed<1?`Je hebt minder dan een 1 nodig (${needed.toFixed(2)}).`:`Je hebt ongeveer een ${needed.toFixed(2)} nodig.`):'Vul geldige waarden in.'};root.querySelectorAll('input').forEach(i=>i.oninput=calc);root.querySelector('.stp-mini-close').onclick=()=>root.remove();calc()}
function openCommandPalette(){if(document.querySelector('#stp-command'))return;const root=document.createElement('div');root.id='stp-command';const actions=[['Somtoday PLUS+ instellingen','Open het uitgebreide instellingenmenu','settings'],['Focusmodus','Maak de interface rustiger','focusMode'],['Privacymodus','Vervaag cijfers','privacyMode'],['Compacte weergave','Toon meer op je scherm','compact'],['Cijferdoel berekenen','Bereken welk cijfer je nodig hebt','calculator'],['Klok tonen','Toon een kleine klok','showClock'],['Rooster compacter','Maak roosteritems compacter','scheduleCompact'],['Selecteerbare tekst','Maak tekst makkelijker selecteerbaar','selectableText']];root.innerHTML=`<div class="stp-command-box"><div class="stp-command-search"><span>⌕</span><input autofocus placeholder="Zoek een PLUS+ actie…"><kbd>ESC</kbd></div><div class="stp-command-list"></div><div class="stp-command-foot">Somtoday PLUS+ · Ctrl + K</div></div>`;document.body.appendChild(root);const input=root.querySelector('input'),list=root.querySelector('.stp-command-list');function render(){const q=input.value.toLowerCase().trim();list.innerHTML='';actions.filter(a=>(a[0]+' '+a[1]).toLowerCase().includes(q)).forEach(a=>{const b=document.createElement('button');b.innerHTML=`<span class="stp-command-action-icon">${a[2]==='settings'?'⚙':a[2]==='calculator'?'#':'✦'}</span><span><b>${a[0]}</b><small>${a[1]}</small></span>`;b.onclick=()=>{root.remove();if(a[2]==='settings')SomtodayPlusNativeSettings?.open()||SomtodayPlusSettings?.openFallback();else if(a[2]==='calculator')gradeCalculator();else toggleQuick(a[2],a[0])};list.appendChild(b)});if(!list.children.length)list.innerHTML='<div class="stp-command-empty">Geen acties gevonden</div>'}input.oninput=render;root.onclick=e=>{if(e.target===root)root.remove()};render()}
document.addEventListener('keydown',async e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){const s=await S();if(!s?.quickCommand)return;e.preventDefault();openCommandPalette()}if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='s'){e.preventDefault();SomtodayPlusNativeSettings?.open()||SomtodayPlusSettings?.openFallback()}if(e.key==='Escape'){document.querySelector('#stp-command')?.remove();document.querySelector('#stp-grade-calc')?.remove()}});
window.addEventListener('stp:settings',apply);chrome.storage.onChanged.addListener(apply);new MutationObserver(()=>{decorate();S().then(applyAlias)}).observe(document.documentElement,{childList:true,subtree:true});apply();window.SomtodayPlusEnhancements={apply,toast,openCommandPalette,gradeCalculator};
})();