(function(){
'use strict';
var lastTitle=null,clockTimer=null;
var FONT_MAP={system:'Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif',inter:'Inter,system-ui,sans-serif',roboto:'Roboto,Arial,sans-serif',poppins:'Poppins,Inter,sans-serif',serif:'Georgia,"Times New Roman",serif',mono:'ui-monospace,SFMono-Regular,Consolas,monospace'};
function S(){return window.SomtodayPlusStorage.get();}
function setClass(name,on){document.documentElement.classList.toggle(name,!!on);}
function weekNumber(d){d=d||new Date();var date=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));date.setUTCDate(date.getUTCDate()+4-(date.getUTCDay()||7));var start=new Date(Date.UTC(date.getUTCFullYear(),0,1));return Math.ceil((((date-start)/86400000)+1)/7);}
function decorate(){document.querySelectorAll('sl-rooster-item,[class*=rooster-item],[class*=afspraak]').forEach(function(el){el.classList.add('stp-enhanced-schedule-item');});document.querySelectorAll('.cijfer,[class*=cijfer]').forEach(function(el){el.classList.add('stp-grade-target');});document.querySelectorAll('[class*=huiswerk],[class*=homework]').forEach(function(el){el.classList.add('stp-homework-target');});document.querySelectorAll('[class*=toets],[class*=exam],[class*=proefwerk]').forEach(function(el){el.classList.add('stp-exam-target');});}
function applyTitle(s){if(s.customTitleEnabled&&String(s.customTitle||'').trim()){if(lastTitle===null)lastTitle=document.title;document.title=String(s.customTitle).trim();}else if(lastTitle!==null){document.title=lastTitle;lastTitle=null;}}
function applyCustomCss(s){var style=document.getElementById('stp-custom-css');if(!s.customCssEnabled||!String(s.customCss||'').trim()){if(style)style.remove();return;}if(!style){style=document.createElement('style');style.id='stp-custom-css';document.head.appendChild(style);}style.textContent=s.customCss;}
function updateClock(s){var el=document.getElementById('stp-clock-chip');if(!s.showClock&&!s.showWeekNumber){if(el)el.remove();if(clockTimer){clearInterval(clockTimer);clockTimer=null;}return;}if(!el){el=document.createElement('div');el.id='stp-clock-chip';document.body.appendChild(el);}var now=new Date(),parts=[];if(s.showClock)parts.push(now.toLocaleTimeString('nl-NL',{hour:'2-digit',minute:'2-digit'}));if(s.showWeekNumber)parts.push('week '+weekNumber(now));el.textContent=parts.join(' · ');if(!clockTimer)clockTimer=setInterval(function(){S().then(updateClock);},30000);}
async function apply(){var s=await S(),r=document.documentElement;if(!s)return;var active=!!s.enabled;var map={'stp-privacy':s.privacyMode,'stp-privacy-hover':s.privacyHoverReveal,'stp-focus':s.focusMode,'stp-selectable':s.selectableText,'stp-hide-scrollbar':s.hideScrollbar,'stp-sticky-topbar':s.stickyTopbar,'stp-dim-weekends':s.dimWeekends||s.weekendFade,'stp-schedule-accent':s.scheduleAccent,'stp-schedule-compact':s.scheduleCompact,'stp-current-lesson':s.currentLessonHighlight,'stp-hide-unread':s.hideUnreadBadge,'stp-hide-profile':s.hideProfilePicture,'stp-hide-side-labels':s.hideSideLabels,'stp-sidebar-compact':s.sidebarCompact,'stp-page-transitions':s.pageTransitions&&!s.reduceMotion,'stp-button-animations':s.buttonAnimations&&!s.reduceMotion,'stp-homework-highlight':s.homeworkHighlight,'stp-exam-highlight':s.examHighlight,'stp-grade-coloring':s.gradeColoring,'stp-grade-reveal':s.gradeReveal&&!s.reduceMotion,'stp-dyslexia':s.dyslexiaFriendly,'stp-large-targets':s.largerClickTargets,'stp-underline-links':s.underlineLinks,'stp-dev-outline':s.devOutline,'stp-highlight-today':s.highlightToday,'stp-hide-cancelled':s.hideCancelledLessons,'stp-fade-past':s.fadePastLessons,'stp-bad-grade':s.emphasizeInsufficientGrades,'stp-privacy-names':s.privacyBlurNames,'stp-privacy-schedule':s.privacyBlurSchedule,'stp-reduce-noise':s.reduceVisualNoise,'stp-dim-secondary':s.dimSecondaryText};Object.keys(map).forEach(function(k){setClass(k,active&&map[k]);});r.style.setProperty('--stp-font-family',FONT_MAP[s.fontFamily]||FONT_MAP.system);r.setAttribute('data-stp-menu-density',s.menuDensity||'normal');applyTitle(active?s:Object.assign({},s,{customTitleEnabled:false}));applyCustomCss(active?s:{customCssEnabled:false});updateClock(active?s:{showClock:false,showWeekNumber:false});decorate();}
function toast(text){var t=document.querySelector('.stp-toast');if(!t){t=document.createElement('div');t.className='stp-toast';document.body.appendChild(t);}t.textContent=text;t.classList.remove('show');requestAnimationFrame(function(){t.classList.add('show');});clearTimeout(t._timer);t._timer=setTimeout(function(){t.classList.remove('show');},2200);}
function gradeCalculator(){if(document.getElementById('stp-grade-calc'))return;var root=document.createElement('div');root.id='stp-grade-calc';root.innerHTML='<div><button class="stp-mini-close">×</button><h3>Cijferdoel berekenen</h3><p>Bereken welk cijfer je ongeveer nodig hebt.</p><label>Huidig gemiddelde<input data-c="avg" type="number" step=".01" value="6.5"></label><label>Huidige totale weging<input data-c="weight" type="number" step=".1" value="10"></label><label>Nieuwe toets weging<input data-c="newWeight" type="number" step=".1" value="1"></label><label>Gewenst gemiddelde<input data-c="target" type="number" step=".01" value="7"></label><output></output></div>';document.body.appendChild(root);function calc(){function g(k){return Number(root.querySelector('[data-c="'+k+'"]').value);}var nw=g('newWeight'),needed=((g('target')*(g('weight')+nw))-(g('avg')*g('weight')))/nw;root.querySelector('output').textContent=Number.isFinite(needed)?'Ongeveer '+needed.toFixed(2)+' nodig.':'Vul geldige waarden in.';}root.querySelectorAll('input').forEach(function(i){i.addEventListener('input',calc);});root.querySelector('.stp-mini-close').addEventListener('click',function(){root.remove();});calc();}
function openCommandPalette(){if(document.getElementById('stp-command'))return;var root=document.createElement('div');root.id='stp-command';var actions=[['PLUS+ instellingen','Open het instellingenmenu',function(){if(window.SomtodayPlusNativeSettings)window.SomtodayPlusNativeSettings.open();}],['Cijferdoel berekenen','Open de rekentool',gradeCalculator],['Focusmodus','Zet focusmodus om',async function(){var s=await S();await SomtodayPlusStorage.set({focusMode:!s.focusMode});}],['Privacymodus','Zet privacymodus om',async function(){var s=await S();await SomtodayPlusStorage.set({privacyMode:!s.privacyMode});}]];root.innerHTML='<div class="stp-command-box"><div class="stp-command-search"><span>⌕</span><input autofocus placeholder="Zoek een actie…"><kbd>ESC</kbd></div><div class="stp-command-list"></div><div class="stp-command-foot">Somtoday PLUS+ · Ctrl + K</div></div>';document.body.appendChild(root);var input=root.querySelector('input'),list=root.querySelector('.stp-command-list');function render(){var q=input.value.toLowerCase();list.innerHTML='';actions.filter(function(a){return (a[0]+' '+a[1]).toLowerCase().includes(q);}).forEach(function(a){var b=document.createElement('button');b.innerHTML='<span class="stp-command-action-icon">✦</span><span><b>'+a[0]+'</b><small>'+a[1]+'</small></span>';b.addEventListener('click',function(){root.remove();a[2]();});list.appendChild(b);});}input.addEventListener('input',render);root.addEventListener('click',function(e){if(e.target===root)root.remove();});render();}
document.addEventListener('keydown',async function(e){var s=await S();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&s.quickCommand&&s.keyboardShortcuts){e.preventDefault();openCommandPalette();}if(e.ctrlKey&&e.altKey&&e.key.toLowerCase()==='s'&&s.keyboardShortcuts){e.preventDefault();if(window.SomtodayPlusNativeSettings)window.SomtodayPlusNativeSettings.open();}if(e.key==='Escape'&&s.escapeClosesDialogs){var a=document.getElementById('stp-command'),b=document.getElementById('stp-grade-calc');if(a)a.remove();if(b)b.remove();}});
window.addEventListener('stp:settings',apply);chrome.storage.onChanged.addListener(apply);var pending=false;new MutationObserver(function(){if(pending)return;pending=true;requestAnimationFrame(function(){pending=false;decorate();});}).observe(document.documentElement,{childList:true,subtree:true});apply();window.SomtodayPlusEnhancements={apply:apply,toast:toast,openCommandPalette:openCommandPalette,gradeCalculator:gradeCalculator};
})();