(()=>{
'use strict';
const TAB_ID='stp-native-settings-tab';
const PANEL_ID='stp-native-settings-panel';
let currentModal=null;
const visible=el=>!!(el&&el.isConnected&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length));
function findHeader(modal){const hs=[...modal.querySelectorAll('sl-account-modal-header .title,.title.ng-star-inserted')];return hs.reverse().find(visible)||hs[0]||null}
function restoreNative(modal){if(!modal)return;modal.querySelector(`#${PANEL_ID}`)?.remove();modal.querySelectorAll('[data-stp-native-hidden="1"]').forEach(el=>{el.style.display=el.dataset.stpOldDisplay||'';delete el.dataset.stpNativeHidden;delete el.dataset.stpOldDisplay});const h=findHeader(modal);if(h?.dataset.stpOriginalTitle){h.textContent=h.dataset.stpOriginalTitle;delete h.dataset.stpOriginalTitle}modal.querySelector(`#${TAB_ID}`)?.classList.remove('active')}
function hideNativeContent(modal){const content=modal.querySelector('.content');if(!content)return null;const host=content.children[0]||content;[...host.children].forEach(child=>{if(child.id===PANEL_ID)return;child.dataset.stpNativeHidden='1';child.dataset.stpOldDisplay=child.style.display||'';child.style.display='none'});return host}
function open(modal){currentModal=modal;restoreNative(modal);modal.querySelectorAll('sl-account-modal-tab').forEach(tab=>{tab.classList.toggle('active',tab.id===TAB_ID);tab.setAttribute('aria-selected',tab.id===TAB_ID?'true':'false')});const h=findHeader(modal);if(h){h.dataset.stpOriginalTitle=h.dataset.stpOriginalTitle||h.textContent;h.textContent='Somtoday PLUS+ instellingen'}const container=modal.querySelector('.container');if(innerWidth<=767&&container)container.classList.add('show-details');const host=hideNativeContent(modal);if(host&&window.SomtodayPlusSettings){const panel=document.createElement('div');panel.id=PANEL_ID;panel.className='stp-native-panel';host.appendChild(panel);window.SomtodayPlusSettings.render(panel,{native:true,modal})}else window.SomtodayPlusSettings?.openFallback()}
function gear(){return '<span class="stp-native-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a2 2 0 0 1 2 2v.36c.75.2 1.45.5 2.08.88l.25-.25a2 2 0 1 1 2.83 2.83l-.25.25c.38.64.68 1.34.88 2.08H20a2 2 0 1 1 0 4h-.36a8 8 0 0 1-.88 2.08l.25.25a2 2 0 1 1-2.83 2.83l-.25-.25a8 8 0 0 1-2.08.88V20a2 2 0 1 1-4 0v-.36a8 8 0 0 1-2.08-.88l-.25.25a2 2 0 1 1-2.83-2.83l.25-.25A8 8 0 0 1 4.36 14H4a2 2 0 1 1 0-4h.36c.2-.75.5-1.45.88-2.08l-.25-.25A2 2 0 1 1 7.82 4.84l.25.25A8 8 0 0 1 10.15 4.2V4a2 2 0 0 1 2-2Zm0 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z"/></svg></span>'}
function inject(modal){if(!modal||modal.querySelector(`#${TAB_ID}`))return;const nav=modal.querySelector('nav'),tabs=modal.querySelectorAll('sl-account-modal-tab');if(!nav||!tabs.length)return;const tab=tabs[tabs.length-1].cloneNode(true);tab.id=TAB_ID;tab.classList.remove('active');tab.setAttribute('aria-selected','false');const label=tab.querySelector('span');if(label)label.textContent='Somtoday PLUS+';const icon=tab.querySelector('i');if(icon){icon.innerHTML=gear();icon.classList.add('stp-native-icon-holder')}else tab.insertAdjacentHTML('afterbegin',gear());tab.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(modal)});nav.appendChild(tab);tabs.forEach(nativeTab=>nativeTab.addEventListener('click',()=>restoreNative(modal)))}
function scan(){document.querySelectorAll('sl-account-modal').forEach(inject)}
new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});scan();
window.SomtodayPlusNativeSettings={scan,open(){const modal=[...document.querySelectorAll('sl-account-modal')].find(visible)||document.querySelector('sl-account-modal');if(!modal)return false;inject(modal);open(modal);return true},restore(){restoreNative(currentModal)}};
})();