(function(){
'use strict';
var TAB_ID='stp-native-settings-tab';
var PANEL_ID='stp-native-settings-panel';
var LABELS=['Mijn gegevens','Weergave','Toestemmingen','Agenda'];
var restoring=false;
function visible(el){return !!(el&&el.isConnected&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length));}
function findModal(){var all=Array.prototype.slice.call(document.querySelectorAll('sl-account-modal'));return all.find(visible)||all[0]||null;}
function findHeader(modal){if(!modal)return null;var items=Array.prototype.slice.call(modal.querySelectorAll('sl-account-modal-header .title,.title.ng-star-inserted,.title'));return items.find(visible)||items[0]||null;}
function getHost(modal){var content=modal&&modal.querySelector('.content');if(!content)return null;return content.children[0]||content;}
function restoreNative(modal){if(!modal||restoring)return;restoring=true;var panel=modal.querySelector('#'+PANEL_ID);if(panel)panel.remove();modal.querySelectorAll('[data-stp-hidden="1"]').forEach(function(el){el.style.display=el.getAttribute('data-stp-display')||'';el.removeAttribute('data-stp-hidden');el.removeAttribute('data-stp-display');});var h=findHeader(modal);if(h&&h.hasAttribute('data-stp-title')){h.textContent=h.getAttribute('data-stp-title');h.removeAttribute('data-stp-title');}var plus=modal.querySelector('#'+TAB_ID);if(plus){plus.classList.remove('active');plus.setAttribute('aria-selected','false');}modal.classList.remove('stp-plus-open');restoring=false;}
function openPlus(modal){if(!modal)return false;restoreNative(modal);var host=getHost(modal);if(!host||!window.SomtodayPlusSettings)return false;modal.classList.add('stp-plus-open');modal.querySelectorAll('sl-account-modal-tab').forEach(function(tab){var active=tab.id===TAB_ID;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',active?'true':'false');});var h=findHeader(modal);if(h){if(!h.hasAttribute('data-stp-title'))h.setAttribute('data-stp-title',h.textContent||'Instellingen');h.textContent='Somtoday PLUS+';}Array.prototype.slice.call(host.children).forEach(function(child){if(child.id===PANEL_ID)return;child.setAttribute('data-stp-hidden','1');child.setAttribute('data-stp-display',child.style.display||'');child.style.display='none';});var panel=document.createElement('div');panel.id=PANEL_ID;panel.className='stp-native-panel';host.appendChild(panel);window.SomtodayPlusSettings.render(panel);return true;}
function relabel(tabs){tabs.forEach(function(tab,index){var span=tab.querySelector('span');if(span&&LABELS[index])span.textContent=LABELS[index];tab.classList.add('stp-native-redesigned-tab');});}
function makePlusTab(modal,nav,tabs){if(modal.querySelector('#'+TAB_ID))return;var base=tabs[tabs.length-1];if(!base)return;var tab=base.cloneNode(true);tab.id=TAB_ID;tab.classList.remove('active');tab.classList.add('stp-plus-tab');tab.setAttribute('aria-selected','false');var label=tab.querySelector('span');if(label)label.textContent='Somtoday PLUS+';var icon=tab.querySelector('i');if(icon){icon.innerHTML='<span class="stp-native-plus-icon">+</span>';icon.classList.add('stp-native-plus-holder');}tab.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();openPlus(modal);});nav.appendChild(tab);}
function inject(modal){if(!modal)return;var nav=modal.querySelector('nav');if(!nav)return;var tabs=Array.prototype.slice.call(nav.querySelectorAll('sl-account-modal-tab')).filter(function(t){return t.id!==TAB_ID;});if(!tabs.length)return;modal.classList.add('stp-account-redesign');nav.classList.add('stp-account-tabs');relabel(tabs);makePlusTab(modal,nav,tabs);tabs.forEach(function(tab){if(tab.getAttribute('data-stp-bound')==='1')return;tab.setAttribute('data-stp-bound','1');tab.addEventListener('click',function(){restoreNative(modal);});});}
function scan(){document.querySelectorAll('sl-account-modal').forEach(inject);}
var pending=false;var observer=new MutationObserver(function(){if(pending)return;pending=true;requestAnimationFrame(function(){pending=false;scan();});});
observer.observe(document.documentElement,{childList:true,subtree:true});scan();
window.SomtodayPlusNativeSettings={scan:scan,open:function(){var modal=findModal();if(!modal)return false;inject(modal);return openPlus(modal);},restore:function(){var modal=findModal();if(modal)restoreNative(modal);}};
})();