(()=>{
'use strict';
const TAB_ID='stp-native-settings-tab',PANEL_ID='stp-native-settings-panel';let currentModal=null;
const visible=el=>!!(el&&el.isConnected&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length));
const LABELS=['Mijn gegevens','Weergave','Toestemmingen','Agenda'];
function findHeader(modal){return [...modal.querySelectorAll('sl-account-modal-header .title,.title.ng-star-inserted')].reverse().find(visible)||null}
function restoreNative(modal){if(!modal)return;modal.querySelector(`#${PANEL_ID}`)?.remove();modal.querySelectorAll('[data-stp-native-hidden="1"]').forEach(el=>{el.style.display=el.dataset.stpOldDisplay||'';delete el.dataset.stpNativeHidden;delete el.dataset.stpOldDisplay});const h=findHeader(modal);if(h?.dataset.stpOriginalTitle){h.textContent=h.dataset.stpOriginalTitle;delete h.dataset.stpOriginalTitle}modal.querySelector(`#${TAB_ID}`)?.classList.remove('active');modal.classList.remove('stp-plus-open')}
function hideNativeContent(modal){const content=modal.querySelector('.content');if(!content)return null;const host=content.children[0]||content;[...host.children].forEach(child=>{if(child.id===PANEL_ID)return;child.dataset.stpNativeHidden='1';child.dataset.stpOldDisplay=child.style.display||'';child.style.display='none'});return host}
function open(modal){currentModal=modal;restoreNative(modal);modal.classList.add('stp-plus-open');modal.querySelectorAll('sl-account-modal-tab').forEach(tab=>{const on=tab.id===TAB_ID;tab.classList.toggle('active',on);tab.setAttribute('aria-selected',String(on))});const h=findHeader(modal);if(h){h.dataset.stpOriginalTitle=h.dataset.stpOriginalTitle||h.textContent;h.textContent='Somtoday PLUS+'}const container=modal.querySelector('.container');if(innerWidth<=767&&container)container.classList.add('show-details');const host=hideNativeContent(modal);if(host&&window.SomtodayPlusSettings){const panel=document.createElement('div');panel.id=PANEL_ID;panel.className='stp-native-panel';host.appendChild(panel);SomtodayPlusSettings.render(panel)}else SomtodayPlusSettings?.openFallback()}
function icon(){return '<span class="stp-native-plus-icon">+</span>'}
function labelNativeTabs(modal){const tabs=[...modal.querySelectorAll('sl-account-modal-tab')].filter(t=>t.id!==TAB_ID);tabs.forEach((tab,i)=>{tab.classList.add('stp-native-redesigned-tab');const span=tab.querySelector('span');if(span&&LABELS[i])span.textContent=LABELS[i];tab.dataset.stpTabIndex=String(i)});return tabs}
function inject(modal){if(!modal)return;const nav=modal.querySelector('nav'),tabs=labelNativeTabs(modal);if(!nav||!tabs.length)return;nav.classList.add('stp-account-tabs');if(!modal.querySelector(`#${TAB_ID}`)){const tab=tabs[tabs.length-1].cloneNode(true);tab.id=TAB_ID;tab.classList.remove('active');tab.classList.add('stp-plus-tab');tab.setAttribute('aria-selected','false');const span=tab.querySelector('span');if(span)span.textContent='Somtoday PLUS+';const i=tab.querySelector('i');if(i)i.innerHTML=icon();else tab.insertAdjacentHTML('afterbegin',icon());tab.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();open(modal)});nav.appendChild(tab)}tabs.forEach(tab=>{if(tab.dataset.stpRestoreBound)return;tab.dataset.stpRestoreBound='1';tab.addEventListener('click',()=>restoreNative(modal))});modal.classList.add('stp-account-redesign')}
function scan(){document.querySelectorAll('sl-account-modal').forEach(inject)}
new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true});scan();
window.SomtodayPlusNativeSettings={scan,open(){const modal=[...document.querySelectorAll('sl-account-modal')].find(visible)||document.querySelector('sl-account-modal');if(!modal)return false;inject(modal);open(modal);return true},restore(){restoreNative(currentModal)}};
})();