(function(){
'use strict';
var VERSION=chrome.runtime.getManifest().version;
var OVERLAY_ID='stp-settings-overlay';
var groups=[
 {title:'Algemeen',desc:'De belangrijkste PLUS+ opties.',items:[['toggle','enabled','Somtoday PLUS+','Zet alle PLUS+ functies aan of uit.'],['toggle','quickCommand','Ctrl + K snelmenu','Open snel acties vanuit elke Somtoday-pagina.'],['toggle','stickyTopbar','Bovenbalk vastzetten','Houd de bovenste balk zichtbaar tijdens scrollen.'],['toggle','showClock','Klok tonen','Toon een compacte klok rechtsonder.'],['toggle','showWeekNumber','Weeknummer tonen','Voeg het huidige weeknummer toe.']]},
 {title:'Weergave',desc:'Maak Somtoday rustiger, duidelijker of persoonlijker.',items:[['color','accent','Accentkleur','Kleur voor PLUS+ accenten.'],['select','fontFamily','Lettertype','Kies een lettertypestijl.',[['system','Systeem'],['inter','Inter'],['roboto','Roboto'],['poppins','Poppins'],['serif','Serif'],['mono','Monospace']]],['range','fontScale','Tekstgrootte','Schaal de interface.',0.88,1.18,0.01],['range','cardGap','Ruimte tussen kaarten','Pas witruimte aan.',5,24,1],['toggle','rounded','Rondere interface','Gebruik zachtere hoeken.'],['toggle','softCards','Zachte kaarten','Geef kaarten een subtiele tint.'],['toggle','shadows','Schaduwen','Voeg rustige diepte toe.'],['toggle','glass','Glas-effect','Gebruik transparantie en blur.'],['toggle','compact','Compacte weergave','Toon meer informatie tegelijk.'],['toggle','highContrast','Meer contrast','Maak tekst en randen duidelijker.']]},
 {title:'Achtergrond',desc:'Pas de pagina-achtergrond aan.',items:[['toggle','gradient','Gradient achtergrond','Gebruik twee kleuren als achtergrond.'],['color','gradientA','Gradient kleur 1','Eerste kleur.'],['color','gradientB','Gradient kleur 2','Tweede kleur.'],['range','gradientAngle','Gradient richting','Draai de richting.',0,360,1],['toggle','blurBackgroundPanels','Transparante panelen','Laat de achtergrond subtiel doorschijnen.']]},
 {title:'Menu & navigatie',desc:'Maak navigatie makkelijker te gebruiken.',items:[['toggle','sidebarCompact','Compacte zijbalk','Maak navigatie compacter.'],['toggle','hideSideLabels','Verberg zijbalktekst','Laat vooral iconen zien.'],['toggle','hideUnreadBadge','Verberg ongelezen teller','Verberg ondersteunde badges.'],['select','menuDensity','Menuhoogte','Kies de ruimte per item.',[['compact','Compact'],['normal','Normaal'],['comfortable','Ruim']]],['toggle','largerClickTargets','Grotere klikdoelen','Maak knoppen makkelijker aanklikbaar.']]},
 {title:'Rooster',desc:'Handige verbeteringen voor je schooldag.',items:[['toggle','scheduleAccent','Roosteraccent','Geef lessen een duidelijk accent.'],['toggle','scheduleCompact','Compact rooster','Maak roosteritems compacter.'],['toggle','currentLessonHighlight','Huidige les benadrukken','Laat de actuele les extra opvallen.'],['toggle','highlightToday','Vandaag benadrukken','Maak de huidige dag duidelijker.'],['toggle','weekendFade','Weekenden rustiger','Dim weekendkolommen.'],['toggle','homeworkHighlight','Huiswerk markeren','Maak huiswerk beter herkenbaar.'],['toggle','examHighlight','Toetsen markeren','Geef toetsen extra nadruk.'],['toggle','hideCancelledLessons','Geannuleerde lessen verbergen','Verberg herkenbare geannuleerde items.'],['toggle','fadePastLessons','Afgelopen lessen dimmen','Maak oude lessen rustiger.']]},
 {title:'Cijfers',desc:'Maak cijfers overzichtelijker.',items:[['toggle','gradeColoring','Cijferaccenten','Geef cijferblokken een rustige hoverstijl.'],['toggle','gradeReveal','Cijfer reveal','Gebruik een subtiele verschijnanimatie.'],['toggle','emphasizeInsufficientGrades','Onvoldoendes benadrukken','Maak herkenbare onvoldoendes duidelijker.'],['action','gradeCalc','Cijferdoel berekenen','Bereken welk cijfer je ongeveer nodig hebt.']]},
 {title:'Focus & privacy',desc:'Minder afleiding en meer privacy.',items:[['toggle','focusMode','Focusmodus','Maak secundaire onderdelen rustiger.'],['toggle','reduceVisualNoise','Minder visuele ruis','Dim niet-essentiële onderdelen.'],['toggle','privacyMode','Privacymodus','Vervaag cijfers en gemiddelden.'],['toggle','privacyHoverReveal','Tonen bij hover','Toon verborgen informatie bij hover.'],['toggle','privacyBlurNames','Namen vervagen','Vervaag herkenbare namen.'],['toggle','privacyBlurSchedule','Rooster vervagen','Vervaag roosteritems.'],['toggle','hideProfilePicture','Profielfoto verbergen','Verberg ondersteunde profielfoto’s.']]},
 {title:'Browser & toegankelijkheid',desc:'Kleine maar handige verbeteringen.',items:[['toggle','customTitleEnabled','Eigen tabbladtitel','Gebruik een eigen titel.'],['text','customTitle','Tabbladtitel','Bijvoorbeeld School · Somtoday PLUS+.'],['toggle','selectableText','Tekst selecteerbaar','Maak tekst selecteerbaar.'],['toggle','hideScrollbar','Scrollbar verbergen','Scrollen blijft werken.'],['toggle','reduceMotion','Minder beweging','Beperk PLUS+ animaties.'],['toggle','dyslexiaFriendly','Extra leesruimte','Meer letter- en woordruimte.'],['toggle','underlineLinks','Links onderstrepen','Maak links herkenbaarder.'],['toggle','openLinksNewTab','Externe links nieuw tabblad','Open externe websites apart.']]},
 {title:'Geavanceerd',desc:'Voor extra aanpassingen en backup.',items:[['toggle','customCssEnabled','Aangepaste CSS','Gebruik eigen CSS bovenop PLUS+.'],['textarea','customCss','Custom CSS','Alleen gebruiken als je CSS kent.'],['toggle','devOutline','Debug-randen','Toon interface-randen voor ontwikkeling.']]}
];
function esc(v){var d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML;}
function itemHtml(it){var type=it[0],key=it[1],label=it[2],desc=it[3],a=it[4],b=it[5],c=it[6],search=esc((label+' '+desc).toLowerCase());if(type==='toggle')return '<label class="stp-setting-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><input class="stp-switch" type="checkbox" data-key="'+key+'"></label>';if(type==='color')return '<label class="stp-setting-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><span class="stp-color-wrap"><input type="color" data-key="'+key+'"><code data-color-for="'+key+'"></code></span></label>';if(type==='range')return '<label class="stp-setting-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><span class="stp-range-wrap"><input type="range" min="'+a+'" max="'+b+'" step="'+c+'" data-key="'+key+'"><output data-output-for="'+key+'"></output></span></label>';if(type==='text')return '<label class="stp-setting-row stp-text-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><input class="stp-text-input" type="text" data-key="'+key+'"></label>';if(type==='textarea')return '<label class="stp-setting-row stp-area-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><textarea data-key="'+key+'" spellcheck="false"></textarea></label>';if(type==='select')return '<label class="stp-setting-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><select data-key="'+key+'">'+a.map(function(o){return '<option value="'+esc(o[0])+'">'+esc(o[1])+'</option>';}).join('')+'</select></label>';if(type==='action')return '<div class="stp-setting-row" data-search="'+search+'"><span><b>'+label+'</b><small>'+desc+'</small></span><button class="stp-inline-action" data-action="'+key+'">Open</button></div>';return '';}
function groupHtml(g,index){return '<section class="stp-scroll-section"><div class="stp-section-heading"><div><span class="stp-section-index">'+String(index+1).padStart(2,'0')+'</span><h3>'+g.title+'</h3><p>'+g.desc+'</p></div></div><div class="stp-settings-card">'+g.items.map(itemHtml).join('')+'</div></section>';}
async function render(target){var state=await SomtodayPlusStorage.get();target.classList.add('stp-settings-root');target.innerHTML='<div class="stp-scroll-settings"><header class="stp-scroll-header"><div class="stp-scroll-brand"><span class="stp-settings-logo">+</span><div><small>SOMTODAY PLUS+</small><h2>Instellingen</h2><p>Alles op één duidelijke pagina. Wijzigingen worden direct opgeslagen.</p></div></div><div class="stp-live-badge">● Live</div><div class="stp-scroll-search"><span>⌕</span><input type="search" placeholder="Zoek bijvoorbeeld rooster, cijfers of privacy…"></div></header><div class="stp-scroll-body">'+groups.map(groupHtml).join('')+'<section class="stp-scroll-section"><div class="stp-section-heading"><div><h3>Backup & herstel</h3><p>Bewaar of herstel je PLUS+ instellingen.</p></div></div><div class="stp-action-grid"><button data-action="export"><b>Exporteer instellingen</b><small>Download een JSON-backup.</small></button><button data-action="import"><b>Importeer instellingen</b><small>Lees een eerdere backup in.</small></button><button class="danger" data-action="reset"><b>Reset PLUS+</b><small>Zet alles terug naar standaard.</small></button><input class="stp-import-file" type="file" accept="application/json" hidden></div></section><section class="stp-scroll-section stp-about-section"><div class="stp-about-grid"><div><b>Ctrl + K</b><small>Snelmenu</small></div><div><b>Ctrl + Alt + S</b><small>Open instellingen</small></div><div><b>V'+esc(VERSION)+'</b><small>Somtoday PLUS+</small></div></div></section></div></div>';
 function updateDecor(el,key){if(el.type==='color'){var c=target.querySelector('[data-color-for="'+key+'"]');if(c)c.textContent=el.value.toUpperCase();}if(el.type==='range'){var o=target.querySelector('[data-output-for="'+key+'"]');if(o)o.textContent=key==='fontScale'?Math.round(Number(el.value)*100)+'%':key==='gradientAngle'?el.value+'°':el.value+'px';}}
 target.querySelectorAll('[data-key]').forEach(function(el){var key=el.getAttribute('data-key');if(el.type==='checkbox')el.checked=!!state[key];else el.value=state[key]==null?'':state[key];updateDecor(el,key);el.addEventListener('input',async function(){var value=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;state[key]=value;updateDecor(el,key);var patch={};patch[key]=value;await SomtodayPlusStorage.set(patch);});});
 var search=target.querySelector('.stp-scroll-search input');if(search)search.addEventListener('input',function(){var q=search.value.toLowerCase().trim();target.querySelectorAll('.stp-scroll-section').forEach(function(sec){var rows=Array.prototype.slice.call(sec.querySelectorAll('[data-search]'));if(!rows.length){sec.hidden=!!q&&!sec.textContent.toLowerCase().includes(q);return;}var visibleCount=0;rows.forEach(function(row){var show=!q||row.getAttribute('data-search').includes(q);row.hidden=!show;if(show)visibleCount++;});sec.hidden=!!q&&visibleCount===0;});});
 var calc=target.querySelector('[data-action="gradeCalc"]');if(calc)calc.addEventListener('click',function(){if(window.SomtodayPlusEnhancements)window.SomtodayPlusEnhancements.gradeCalculator();});
 var exp=target.querySelector('[data-action="export"]');if(exp)exp.addEventListener('click',async function(){var raw=await SomtodayPlusStorage.exportSettings(),blob=new Blob([raw],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='somtoday-plus-settings.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);});
 var file=target.querySelector('.stp-import-file'),imp=target.querySelector('[data-action="import"]');if(imp&&file)imp.addEventListener('click',function(){file.click();});if(file)file.addEventListener('change',async function(){if(!file.files||!file.files[0])return;try{await SomtodayPlusStorage.importSettings(await file.files[0].text());render(target);}catch(e){alert('Deze backup kon niet worden geïmporteerd.');}});
 var reset=target.querySelector('[data-action="reset"]');if(reset)reset.addEventListener('click',async function(){if(confirm('Alle Somtoday PLUS+ instellingen resetten?')){await SomtodayPlusStorage.reset();render(target);}});
}
function openFallback(){var old=document.getElementById(OVERLAY_ID);if(old)old.remove();var overlay=document.createElement('div');overlay.id=OVERLAY_ID;overlay.innerHTML='<div class="stp-fallback-shell"><button class="stp-fallback-close" aria-label="Sluiten">×</button><div class="stp-fallback-target"></div></div>';document.body.appendChild(overlay);render(overlay.querySelector('.stp-fallback-target'));overlay.querySelector('.stp-fallback-close').addEventListener('click',function(){overlay.remove();});overlay.addEventListener('click',function(e){if(e.target===overlay)overlay.remove();});return true;}
window.SomtodayPlusSettings={render:render,openFallback:openFallback,open:function(){return window.SomtodayPlusNativeSettings&&window.SomtodayPlusNativeSettings.open()?true:openFallback();}};
})();