(()=>{
'use strict';
const OVERLAY_ID='stp-settings-overlay';
const VERSION=chrome.runtime.getManifest().version;
const esc=v=>{const e=document.createElement('div');e.textContent=v??'';return e.innerHTML};
const sections=[
  {id:'general',title:'Algemeen',desc:'De basis van Somtoday PLUS+.',items:[
    ['toggle','enabled','Somtoday PLUS+','Zet alle PLUS+ functies aan of uit.'],['toggle','quickCommand','Ctrl + K snelmenu','Open overal het PLUS+ command menu.'],['toggle','stickyTopbar','Bovenbalk altijd zichtbaar','Laat de bovenste Somtoday-balk tijdens scrollen staan.'],['toggle','showClock','Klok tonen','Toon rechtsonder een subtiele klok.'],['toggle','showWeekNumber','Weeknummer tonen','Voeg het huidige schoolweeknummer toe aan de klok.']
  ]},
  {id:'appearance',title:'Weergave',desc:'Pas de complete uitstraling van Somtoday aan.',items:[
    ['color','accent','Accentkleur','Kleur voor PLUS+ accenten en highlights.'],['select','fontFamily','Lettertype','Kies de algemene PLUS+ lettertypestijl.',[['system','Systeem'],['inter','Inter'],['roboto','Roboto'],['poppins','Poppins'],['serif','Serif'],['mono','Monospace']]],['range','fontScale','Tekstgrootte','Schaal tekst subtiel mee.',0.88,1.18,0.01],['range','cardGap','Ruimte tussen kaarten','Meer of minder witruimte.',5,24,1],['toggle','rounded','Rondere interface','Rondere kaarten, menu’s en panelen.'],['toggle','softCards','Zachte kaarten','Subtiele achtergrond op ondersteunde kaarten.'],['toggle','shadows','Schaduwen','Voeg meer diepte toe.'],['toggle','glass','Glas-effect','Lichte transparantie en blur waar mogelijk.'],['toggle','compact','Compacte weergave','Toon meer informatie tegelijk.'],['toggle','pageTransitions','Pagina-overgangen','Gebruik zachte overgangen bij ondersteunde pagina’s.'],['toggle','buttonAnimations','Knopanimaties','Maak hover en klikreacties levendiger.'],['toggle','monochromeMode','Monochrome modus','Maak PLUS+ accenten rustiger en neutraler.']
  ]},
  {id:'background',title:'Achtergrond',desc:'Maak de achtergrond persoonlijker.',items:[
    ['toggle','gradient','Gradient achtergrond','Gebruik twee kleuren als pagina-achtergrond.'],['color','gradientA','Gradient kleur 1','Eerste kleur.'],['color','gradientB','Gradient kleur 2','Tweede kleur.'],['range','gradientAngle','Gradient richting','Draai de gradient.',0,360,1],['toggle','blurBackgroundPanels','Transparante panelen','Laat panelen de achtergrond licht doorlaten.']
  ]},
  {id:'menu',title:'Menu & navigatie',desc:'Maak de navigatie rustiger of compacter.',items:[
    ['toggle','sidebarCompact','Compacte zijbalk','Maak de zijbalk smaller en compacter.'],['toggle','hideSideLabels','Verberg zijbalk-tekst','Laat waar mogelijk vooral iconen zien.'],['toggle','hideUnreadBadge','Verberg ongelezen teller','Verberg notificatie-/berichttellers in ondersteunde navigatie.'],['select','menuDensity','Menuhoogte','Kies hoe ruim menu-items zijn.',[['compact','Compact'],['normal','Normaal'],['comfortable','Ruim']]]
  ]},
  {id:'schedule',title:'Rooster',desc:'Verbeter de leesbaarheid van je dag en week.',items:[
    ['toggle','scheduleAccent','Roosteraccent','Geef lessen een subtiel PLUS+ accent.'],['toggle','scheduleCompact','Compact rooster','Maak roosteritems kleiner waar de Somtoday-layout dit toelaat.'],['toggle','currentLessonHighlight','Huidige les benadrukken','Laat actuele/actieve roosteritems extra opvallen.'],['toggle','weekendFade','Weekenden rustiger','Maak weekendkolommen subtieler.'],['toggle','homeworkHighlight','Huiswerk markeren','Geef huiswerkonderdelen een herkenbare rand.'],['toggle','examHighlight','Toetsen markeren','Geef toets/proefwerk-items extra nadruk.']
  ]},
  {id:'grades',title:'Cijfers',desc:'Maak cijfers duidelijker en voeg handige rekentools toe.',items:[
    ['toggle','gradeColoring','Cijferaccenten','Geef cijferblokken een subtiele PLUS+ stijl.'],['toggle','gradeReveal','Cijfer reveal','Laat cijferblokken iets vloeiender verschijnen.'],['action','gradeCalc','Cijferdoel berekenen','Bereken welk cijfer je ongeveer nodig hebt voor een gewenst gemiddelde.']
  ]},
  {id:'focus',title:'Focus & leren',desc:'Haal visuele afleiding weg wanneer je moet werken.',items:[
    ['toggle','focusMode','Focusmodus','Maak secundaire onderdelen rustiger.'],['toggle','dimWeekends','Weekenden dimmen','Maak niet-schooldagen minder opvallend.'],['toggle','reduceMotion','Minder beweging','Schakel PLUS+ beweging grotendeels uit.']
  ]},
  {id:'privacy',title:'Privacy',desc:'Handig wanneer iemand met je meekijkt.',items:[
    ['toggle','privacyMode','Privacymodus','Vervaag cijfers en cijferachtige informatie.'],['toggle','privacyHoverReveal','Tonen bij hover','Laat verborgen informatie tijdelijk zien als je eroverheen gaat.'],['toggle','hideProfilePicture','Profielfoto verbergen','Verberg ondersteunde profielafbeeldingen.']
  ]},
  {id:'profile',title:'Profiel & persoonlijk',desc:'Kleine lokale aanpassingen aan hoe jij Somtoday ziet.',items:[
    ['toggle','aliasEnabled','Eigen weergavenaam','Gebruik lokaal een andere naam op ondersteunde profielplekken.'],['text','displayAlias','Weergavenaam','Deze naam wordt alleen lokaal in jouw browser gebruikt.']
  ]},
  {id:'browser',title:'Browser',desc:'Pas het gedrag van het Somtoday-tabblad aan.',items:[
    ['toggle','customTitleEnabled','Eigen tabbladtitel','Gebruik een eigen titel in de browser.'],['text','customTitle','Tabbladtitel','Bijvoorbeeld School · Somtoday PLUS+.'],['toggle','selectableText','Tekst selecteerbaar','Maak zoveel mogelijk tekst selecteerbaar.'],['toggle','hideScrollbar','Scrollbar verbergen','Scrollen blijft gewoon werken.']
  ]},
  {id:'accessibility',title:'Toegankelijkheid',desc:'Maak PLUS+ prettiger leesbaar en klikbaar.',items:[
    ['toggle','highContrast','Meer contrast','Maak PLUS+ randen en tekst duidelijker.'],['toggle','dyslexiaFriendly','Dyslexie-vriendelijke spacing','Gebruik extra letter- en woordruimte.'],['toggle','largerClickTargets','Grotere klikdoelen','Maak ondersteunde knoppen iets makkelijker aanklikbaar.'],['toggle','underlineLinks','Links onderstrepen','Maak links extra herkenbaar.']
  ]},
  {id:'advanced',title:'Geavanceerd',desc:'Voor gebruikers die Somtoday verder willen aanpassen.',items:[
    ['toggle','customCssEnabled','Aangepaste CSS','Voer eigen CSS uit bovenop PLUS+.'],['textarea','customCss','Custom CSS','Gebruik dit alleen als je weet wat CSS doet.'],['toggle','devOutline','Layout debug-randen','Toon subtiele outlines rond veel interface-elementen.'],['toggle','debugInfo','Debugmodus','Bewaar deze optie voor toekomstige PLUS+ diagnosefuncties.']
  ]}
];
function controlHtml(it){const [type,key,label,desc,a,b,c]=it;const text=`${label} ${desc}`.toLowerCase();if(type==='toggle')return `<label class="stp-setting-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><input class="stp-switch" type="checkbox" data-key="${key}"></label>`;if(type==='color')return `<label class="stp-setting-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><span class="stp-color-wrap"><input type="color" data-key="${key}"><code data-color-for="${key}"></code></span></label>`;if(type==='range')return `<label class="stp-setting-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><span class="stp-range-wrap"><input type="range" min="${a}" max="${b}" step="${c}" data-key="${key}"><output data-output-for="${key}"></output></span></label>`;if(type==='text')return `<label class="stp-setting-row stp-text-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><input class="stp-text-input" type="text" data-key="${key}" autocomplete="off"></label>`;if(type==='textarea')return `<label class="stp-setting-row stp-area-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><textarea data-key="${key}" spellcheck="false" placeholder="/* Jouw CSS */"></textarea></label>`;if(type==='select')return `<label class="stp-setting-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><select data-key="${key}">${a.map(([v,n])=>`<option value="${v}">${n}</option>`).join('')}</select></label>`;if(type==='action')return `<div class="stp-setting-row" data-search="${esc(text)}"><span><b>${label}</b><small>${desc}</small></span><button class="stp-inline-action" data-action="${key}">Open</button></div>`;return ''}
function sectionHtml(s){return `<section class="stp-scroll-section" id="stp-sec-${s.id}" data-section-search="${esc((s.title+' '+s.desc).toLowerCase())}"><div class="stp-section-heading"><div><h3>${s.title}</h3><p>${s.desc}</p></div><span>${(s.items||[]).length}</span></div><div class="stp-settings-card">${s.items.map(controlHtml).join('')}</div></section>`}
function toolsHtml(){return `<section class="stp-scroll-section" id="stp-sec-tools"><div class="stp-section-heading"><div><h3>Presets</h3><p>Pas meerdere instellingen tegelijk toe.</p></div></div><div class="stp-preset-grid"><button data-preset="default"><span>☀</span><b>Standaard+</b><small>Rustige verbeteringen.</small></button><button data-preset="clean"><span>◌</span><b>Clean</b><small>Compact en minimalistisch.</small></button><button data-preset="focus"><span>◎</span><b>Focus</b><small>Voor leren en huiswerk.</small></button><button data-preset="color"><span>✦</span><b>Color</b><small>Gradient en extra diepte.</small></button></div></section><section class="stp-scroll-section"><div class="stp-section-heading"><div><h3>Backup & herstel</h3><p>Bewaar je instellingen of zet ze terug.</p></div></div><div class="stp-action-grid"><button data-action="export"><b>Exporteer instellingen</b><small>Download JSON-backup</small></button><button data-action="import"><b>Importeer instellingen</b><small>Lees een backup in</small></button><button class="danger" data-action="reset"><b>Reset PLUS+</b><small>Terug naar standaard</small></button><input type="file" accept="application/json" class="stp-import-file" hidden></div></section><section class="stp-scroll-section stp-about-section"><div class="stp-section-heading"><div><h3>Over Somtoday PLUS+</h3><p>Versie ${esc(VERSION)} · onafhankelijke browserextensie.</p></div></div><div class="stp-about-grid"><div><b>Ctrl + K</b><small>Snelmenu</small></div><div><b>Ctrl + Alt + S</b><small>Instellingen openen</small></div><div><b>V${esc(VERSION)}</b><small>Somtoday PLUS+</small></div></div></section>`}
async function render(target){const state=await SomtodayPlusStorage.get();target.classList.add('stp-settings-root');target.innerHTML=`<div class="stp-scroll-settings"><header class="stp-scroll-header"><div class="stp-scroll-brand"><span class="stp-settings-logo">+</span><span><small>SOMTODAY PLUS+</small><h2>Instellingen</h2><p>Pas Somtoday helemaal aan. Alles staat op één pagina en wordt direct opgeslagen.</p></span></div><div class="stp-live-badge">● Live</div><div class="stp-scroll-search"><span>⌕</span><input placeholder="Zoek in alle instellingen…"><kbd>Ctrl K</kbd></div></header><div class="stp-scroll-body">${sections.map(sectionHtml).join('')}${toolsHtml()}</div></div>`;
  const scope=target;
  function decor(el,key){if(el.type==='color'){const c=scope.querySelector(`[data-color-for="${key}"]`);if(c)c.textContent=el.value.toUpperCase()}if(el.type==='range'){const o=scope.querySelector(`[data-output-for="${key}"]`);if(o)o.textContent=key==='fontScale'?`${Math.round(Number(el.value)*100)}%`:key==='gradientAngle'?`${el.value}°`:`${el.value}px`}}
  scope.querySelectorAll('[data-key]').forEach(el=>{const key=el.dataset.key;if(el.type==='checkbox')el.checked=!!state[key];else el.value=state[key]??'';decor(el,key);el.addEventListener('input',async()=>{const val=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;state[key]=val;decor(el,key);await SomtodayPlusStorage.set({[key]:val})})});
  const search=scope.querySelector('.stp-scroll-search input');search.addEventListener('input',()=>{const q=search.value.toLowerCase().trim();scope.querySelectorAll('.stp-scroll-section').forEach(sec=>{let matches=0;sec.querySelectorAll('[data-search]').forEach(row=>{const show=!q||row.dataset.search.includes(q);row.hidden=!show;if(show)matches++});const hasRows=sec.querySelector('[data-search]');if(hasRows)sec.hidden=!!q&&matches===0;else sec.hidden=!!q&&!sec.textContent.toLowerCase().includes(q)})});
  const presetMap={default:{compact:false,rounded:true,softCards:true,shadows:true,glass:false,gradient:false,focusMode:false,monochromeMode:false},clean:{compact:true,rounded:true,softCards:true,shadows:false,glass:false,gradient:false,cardGap:8,hideSideLabels:false},focus:{compact:true,rounded:true,softCards:true,shadows:false,gradient:false,focusMode:true,dimWeekends:true,cardGap:8,reduceMotion:true},color:{compact:false,rounded:true,softCards:true,shadows:true,glass:true,gradient:true,gradientA:'#e8f3ff',gradientB:'#f7edff',gradientAngle:135}};
  scope.querySelectorAll('[data-preset]').forEach(b=>b.onclick=async()=>{const p=b.dataset.preset,values={...presetMap[p],lastPreset:p};await SomtodayPlusStorage.set(values);SomtodayPlusEnhancements?.toast(`Preset ${b.querySelector('b').textContent} toegepast`);render(target)});
  scope.querySelector('[data-action="gradeCalc"]')?.addEventListener('click',()=>SomtodayPlusEnhancements?.gradeCalculator());
  scope.querySelector('[data-action="export"]')?.addEventListener('click',async()=>{const raw=await SomtodayPlusStorage.export(),blob=new Blob([raw],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='somtoday-plus-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
  const file=scope.querySelector('.stp-import-file');scope.querySelector('[data-action="import"]')?.addEventListener('click',()=>file?.click());file?.addEventListener('change',async()=>{try{await SomtodayPlusStorage.import(await file.files[0].text());SomtodayPlusEnhancements?.toast('Instellingen geïmporteerd');render(target)}catch{SomtodayPlusEnhancements?.toast('Kon backup niet importeren')}});
  scope.querySelector('[data-action="reset"]')?.addEventListener('click',async()=>{if(confirm('Alle Somtoday PLUS+ instellingen resetten?')){await SomtodayPlusStorage.reset();SomtodayPlusEnhancements?.toast('PLUS+ is gereset');render(target)}});
}
async function openFallback(){document.getElementById(OVERLAY_ID)?.remove();const overlay=document.createElement('div');overlay.id=OVERLAY_ID;overlay.innerHTML='<div class="stp-fallback-shell"><button class="stp-fallback-close">×</button><div class="stp-fallback-target"></div></div>';document.body.appendChild(overlay);await render(overlay.querySelector('.stp-fallback-target'));overlay.querySelector('.stp-fallback-close').onclick=()=>overlay.remove();overlay.onclick=e=>{if(e.target===overlay)overlay.remove()}}
window.SomtodayPlusSettings={render,openFallback,open(){return window.SomtodayPlusNativeSettings?.open()||openFallback()}};
})();